// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDosXbu7UzYfyoPwJlVb_WcSPFj-8LtNq4',
    appId: '1:259667167780:android:78feb51f0be9e331a966b1',
    messagingSenderId: '259667167780',
    projectId: 'zion3-e453d',
    databaseURL: 'https://zion3-e453d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zion3-e453d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIpuehwClYYDMJDmY_EzrjGwHgZHRa6iY',
    appId: '1:259667167780:ios:305dbd50b534fb38a966b1',
    messagingSenderId: '259667167780',
    projectId: 'zion3-e453d',
    databaseURL: 'https://zion3-e453d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zion3-e453d.appspot.com',
    androidClientId: '259667167780-1fpssa6qa54lemm22ufc4bd9cvrd7l73.apps.googleusercontent.com',
    iosClientId: '259667167780-36bkobpafjf5rbabatq8g54m3giutkrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.zionDriver553',
  );
}
